function virtuallyFoveateVideo(world_video, sensor_t_cell, gaze_angles, gaze_offsets, blnk_events, output_path, path_to_intrinsics, options)
% Virtually foveate desired frames of a video with given gaze angles
%
% Syntax:
%   virtuallyFoveateVideo(world_video, gaze_angles, offsets, output_path, path_to_intrinsics, path_to_perspective_projection, options)
%
% Description:
%   This function will virtually foveate a world camera video, given the gaze 
%   angles and offsets thereof associated with this video, as well 
%   as the original recording chunks used to generate it. 
%   It also requires the path to the intrinsics of the world camera  
%   as a camera calibration object and the path to the projection 
%   matrix that maps between screen coordinates and eye coordinates 
%   as generated by calculate_perspective_transform_w2e.m.
%   When alinging gaze angles to their associated frame, 
%   we take a nearest neighbors approach based on timestamps. 
%   We also account for a slight phase offset between the world 
%   camera and pupil camera. One may edit this, as well as the 
%   FPS of the pupil camera and the range of frames to virtually foveate. 
%   Gaze angles that are NaN are replaced with an empty frame. 
%      
% Inputs:
%   world_video                    - String. Path to the playable .avi world video
%
%   gaze_angles                    - Matrix Double. Matrix of gaze angles in px [x, y]
%                                    for each frame of the pupil camera
%   
%   gaze_offsets                   - 1x2 or 2x1 Double. Constant offset to be applied 
%                                    to the gaze angles, varies by participant
%
%   output_path                    - String. Path to the playable output .avi video
%
%
%   path_to_intrinscis             - String. Path to the camera calibration intrinsics
%                                    object for the world camera. 
%   
%   path_to_perspective_projection - String. Path to the projection object 
%                                    that maps between screen and eye coordinates. 
%                                    Generated with calculate_perspective_transform_w2e.m
% % Optional key/value pairs:
%   
%  'frames_to_process'             - 2x1 or 1x2 Double array. The range of frames 
%                                    to virtually foveate, inclusive and 1 indexed. 
%   
%  'pupil_fps'                     - Double. The FPS of the pupil camera for this recording
%
%  'pupil_world_phase_offset'      - Double. The phase offset between the pupil and world cameras 
%                                    in seconds. Applied to the pupil camera. Positive implies advanced.     
%   
% Outputs:
%
%   NONE
%
% Examples:
%{

%}

    arguments
        world_video {mustBeText}
        sensor_t_cell
        gaze_angles {mustBeMatrix}
        gaze_offsets {mustBeNumeric}
        blnk_events
        output_path {mustBeText}
        path_to_intrinsics {mustBeText}
        
        options.world_fps = 120
        options.pupil_fps {mustBeNumeric} = 120
        options.nan_deg_threshold = 45
        options.frames_to_process = [1, inf]
        options.verbose = false
        options.manual_offset = [0, 0]
        options.non_contiguous_target_frames = []
        options.testing = false
        options.video_read_cache_size = 1000
    end
    % Import the Python util library 
    virutal_foveation_util = import_pyfile(getpref("lightLoggerAnalysis", "virtual_foveation_util_path"));

    % Create a video IO reader wrapper we will use to read/write into the original video
    if(options.verbose)
        disp("Opening video reader/writer")
    end 
    world_frame_reader = videoIOWrapper(world_video,... 
                                        "ioAction", 'read', ...
                                        "readAheadBufferSize", options.video_read_cache_size...
                                        ); 
    world_frame_writer = videoIOWrapper(output_path, "ioAction", 'write'); 
    world_frame_writer.FrameRate = options.world_fps; 

    % Apply the gaze offsets to the gaze angles, and adjust their coordinate system 
    gaze_angles_original = gaze_angles(:, 1:2) - gaze_offsets; 

    % We first subtract the constant gaze offset from the gaze angles (measured once per pariticpant)
    % Then, we flip the signs to be upsidedown and left handed. Then, 
    % we apply a manual offset from the April Tag. The sign of this corresponds to the follow
    % +azi = move right, +ele = move up
    gaze_angles(:, 1:2) = ( ( gaze_angles(:, 1:2) - gaze_offsets ) .* [1, -1] ) + options.manual_offset;

    % Extract world and pupil t 
    world_t = sensor_t_cell{1};
    pupil_t = sensor_t_cell{2};

    % Choose the bounds for our virtual foveation 
    start_frame = options.frames_to_process(1); 
    end_frame = world_frame_reader.NumFrames; 
    if(options.frames_to_process(2) ~= inf)
        end_frame = options.frames_to_process(2);
    end 
    assert(start_frame > 0 && end_frame <= world_frame_reader.NumFrames);

    % Open the writer to start writing frames 
    open(world_frame_writer); 

    % Iterate over the world frames 
    if(options.verbose)
        disp("Beginning frame processing")
    end 
    
    % First, let's find the number of chunks in the portion of the
    % video selected 
    num_chunks = ceil( ( (end_frame - start_frame) + 1) / options.video_read_cache_size);
    current_start = start_frame; 

    % Next, we will iterate over the chunks of the video 
    total_time = tic; 
    for cc = 1:num_chunks
        chunk_time = tic; 
        
        % If verbose, print what chunk we are on
        if(options.verbose)
            fprintf("Processing chunk: %d/%d\n", cc, num_chunks);
        end  


        % Find the end frame for this chunk 
        current_end = min((current_start + options.video_read_cache_size) - 1, end_frame); 

        % Initialize container for the frames to be read in 
        chunk_size = (current_end - current_start) + 1; 
        chunk_frames = zeros(chunk_size, world_frame_reader.Height, world_frame_reader.Width, 3, 'uint8'); 

        % Initialize output buffer that will write to the disk 
        output_buffer = zeros(chunk_size, 480, 480, 3, 'uint8');
        desiredN = size(output_buffer, 2); 

        dq = parallel.pool.DataQueue;
        h = waitbar(0, 'Processing frames...');

        counter = java.util.concurrent.atomic.AtomicInteger(0);
        afterEach(dq, @(~) waitbar(counter.incrementAndGet() / chunk_size, h));

        % Next, let's read in the frames for the chunk 
        input_buffer_insertion_idx = 1; 
        for ff = current_start : current_end; 
            % Force rebuffer every time a chunk starts (should not need to do this, but just for safety)
            force_rebuffer = input_buffer_insertion_idx == 1; 
            
            % Read the frame and insert it into the chunk frames buffer 
            chunk_frames(input_buffer_insertion_idx, :, :, :) = world_frame_reader.readFrame('frameNum', ff,...
                                                                  'color', 'RGB',...
                                                                  'verbose', false,...
                                                                  'force_rebuffer', force_rebuffer...
                                                                ); 

            % Update the insertion index 
            input_buffer_insertion_idx = input_buffer_insertion_idx + 1; 
        end  

        % Now, we read in all the frames. We will now process them in parallel
        parfor pp = 1:size(chunk_frames, 1)
            % Find the global world frame number 
            % that corresponds to this frame 
            global_world_frame_number = (pp + current_start) - 1; 

            % Retrieve the world frame timestamp and frame 
            world_timestamp = world_t(global_world_frame_number); 
            world_frame = squeeze(chunk_frames(pp, :, :, :)); 
            
            % Find the gaze angle that corresponds to this frame 
            [~, gaze_angle_idx] = min(abs(pupil_t - world_timestamp));
            gaze_angle = gaze_angles(gaze_angle_idx, 1:2); 

            % NaN the gaze angle if it's above a large threshold
            if( any(abs(gaze_angle) > options.nan_deg_threshold) )
                gaze_angle(:) = nan;
            end
            
            % If any of the cases for which we should skip a frame are true, just skip and we 
            % will output a blank frame already pre-allocated in the output buffer 
            if(~any(world_frame(:)) || any(isnan(gaze_angle)) || is_blnk_event(pupil_t(gaze_angle_idx), blnk_events))
                send(dq, 1);
                continue
            end 
            
            % Otherwise, virtually foveate the frame 
            virtually_foveated_frame = uint8(virtuallyFoveateFrame(world_frame, gaze_angle, ...
                                                                   path_to_intrinsics, 'desiredN', desiredN...
                                                                   )...
                                            );
            output_buffer(pp, :, :, :) = virtually_foveated_frame; 

            % Add option to apply color weights here 


            % Add option to apply fielding function here

            % Update the wait bar 
            send(dq,1);
        end 

        close(h);

       % Now that all these frames have been processed in parallel, let's write them out to the disk
        for oo = 1:size(output_buffer, 1)
            frame_to_write = squeeze(output_buffer(oo, :, :, :)); 
            world_frame_writer.writeVideo(frame_to_write); 
        end 

        % Update the start for the next chunk 
        current_start = current_start + chunk_size;
        
        chunk_elapsed_seconds = toc(chunk_time);
        fprintf("Chunk elpased time: %f seconds\n", chunk_elapsed_seconds);

    end 

    % Close the world video writer 
    close(world_frame_writer); 

    elapsed_seconds = toc(total_time); 
    fprintf("Total Elapsed Time: %f seconds\n", elapsed_seconds); 

    return; 

end 


% Local function to determine if a given pupil frame timestamp 
% is in a range of blink events 
function is_blink = is_blnk_event(timestamp, blnk_events)
    is_blink = false; 

    % Iterate over the blnk_events
    for rr = 1:size(blnk_events, 1)
        row = blnk_events(rr, :);
        event_start = row(1);
        event_end = row(2);
        
        % If the current event end time is before the current event, we can just skip 
        if(event_end < timestamp)
            continue; 
        end 

        % If the current event start time is after the timestamp 
        % we are searching for, just return early. No event after this 
        % could be a range where this timestamp lies 
        if(event_start > timestamp)
            return; 
        end 

        % If the timestamp is in this range, it is a BLNK event, so 
        % return true 
        if((event_start <= timestamp) && (event_end >= timestamp))
            is_blink = true;
            return ; 
        end 
    end 


    return ; 

end