% This minimal script serves to document the paths to the materials and
% output of the use of the Matlab camera lens calibration app to
% characterize the intrinsics of the IMX219 camera chip equipped with the
% M12 wide-angle lens. A README file located in the
% data/fisheyeLensCalibration directory provides details regarding the
% measurement.

% Housekeeping
clear
addpath(fullfile(fileparts(mfilename('fullpath')), 'utilities'))

% Path to the matlab camera calibration app session file
sessionFileName = fullfile(...
    tbLocateProjectSilent('lightLoggerAnalysis'),...
    'data',...
    'fisheyeLensCalibration',...
    'intrinsics_calibration_session.mat');

% Launch the camera calibration app. After exporting the calibrated result
% to the canonical file, return here so the shared derived-file contract can
% attach and validate its README metadata.
cameraCalibrator(sessionFileName)

projectRoot = tbLocateProjectSilent('lightLoggerAnalysis');
outputPath = fullfile( ...
    projectRoot, 'derived', 'arducamB0392cameraIntrinsics.mat');
input([ ...
    'Export arducamB0392cameraIntrinsics from Camera Calibrator to:\n' ...
    outputPath, '\nThen press Return here to finalize the derived file.'], 's');

assert(isfile(outputPath), ...
    'defineFisheyeCameraIntrinsics:MissingExport', ...
    'The expected Camera Calibrator export was not found: %s', outputPath);
intrinsicsData = load(outputPath, 'arducamB0392cameraIntrinsics');
assert(isfield(intrinsicsData, 'arducamB0392cameraIntrinsics'), ...
    'defineFisheyeCameraIntrinsics:MissingVariable', ...
    ['The exported MAT file must contain the variable ' ...
    'arducamB0392cameraIntrinsics.']);

README = sprintf([ ...
    'Created interactively by defineFisheyeCameraIntrinsics.m using ' ...
    'Camera Calibrator.\n' ...
    'arducamB0392cameraIntrinsics contains the calibrated fisheye model ' ...
    'for the 640-by-480 ArduCam B0392 IMX219 world camera.']);
derivedVariables = struct();
derivedVariables.arducamB0392cameraIntrinsics = ...
    intrinsicsData.arducamB0392cameraIntrinsics;
saveDerivedFile(outputPath, README, derivedVariables);
validateDerivedFilesHaveREADME(fileparts(outputPath));
